env:
  commonjs: true
  node: true
  mocha: true
extends:
  - eslint:recommended
  - airbnb-base
parserOptions:
  ecmaVersion: latest
rules:
  comma-dangle: ["error", "never"]
  object-curly-newline: 0
  no-console: 0
  no-param-reassign: 0
  no-restricted-syntax: 
    - error
    - ForInStatement
    - LabeledStatement
    - WithStatement
