name: publish to NPM registry

on:
  release:
    types: [published]

jobs:
  npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - run: npm ci
      - run: git config --global user.name "GitHub CD bot"
      - run: git config --global user.email "contact@fabco.tech"
      - run: npm version ${{ github.event.release.tag_name }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
